        int x = 24;
        int z = 7 * 4;
        int a = 8;
        int b = 3;
        int amount = 8;
        amount = amount + 1;
        System.out.println(24);
        System.out.println("Two dozen is " + x);
        System.out.println("forty-two is " +z);
        System.out.println(amount);
        System.out.println(a*b); 
